language: node_js
node_js:
  - "lts/*"
  - "8"

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#metabrainz"
    on_success: always
    on_failure: always
    template:
      - "Project %{repository_name} build #%{build_number}: %{result} in %{elapsed_time}: %{build_url}"

sudo: false

cache:
  directories:
    - node_modules

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  postgresql: "9.5"

before_script:
  - psql -c 'CREATE DATABASE bookbrainz_test;' -U postgres
  - psql -c 'CREATE EXTENSION "uuid-ossp"; CREATE SCHEMA musicbrainz; CREATE SCHEMA bookbrainz;' -d bookbrainz_test -U postgres
  - psql -f sql/schemas/musicbrainz.sql -d bookbrainz_test -U postgres
  - psql -f sql/schemas/bookbrainz.sql -d bookbrainz_test -U postgres
  - psql -f sql/scripts/create_triggers.sql -d bookbrainz_test -U postgres
  - ./node_modules/.bin/eslint -v

script:
  - npm run-script test-ci

after_script:
  - npm install -g coveralls && coveralls < coverage/lcov.info
